### ISSUE TITLE
The demo site is down

### ISSUE THREAD

**Issue by pivic** [motifland/markprompt-starter-template#2]
When visiting https://markprompt-starter-template-alpha.vercel.app, this is displayed:

> 404: NOT_FOUND Code: DEPLOYMENT_NOT_FOUND ID: arn1::2l7fl-1682515731348-d92b02a58922
> [markprompt-starter-template-alpha.vercel.app might be available. Click here to learn how to assign it to a project.](https://vercel.com/docs/custom-domains#assigning-a-domain-to-a-git-branch)

**Comment by michaelfester** [comment]
Thanks @pivic and sorry for the delay. Curious, where did you get this link from, so that we can update it? Here is the correct link: https://markprompt-starter-template.vercel.app/.
